# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
# - script: '"C:\Program Files (x86)\Progress\Test Studio\Bin\ArtOfTest.Runner.exe" list="C:\Users\Usman\Documents\Test Studio Projects\spotify\TestLists\spotify page.aiilist" junit'

- task: CmdLine@2
  inputs:
    script: '"C:\Program Files (x86)\Progress\Test Studio\Bin\ArtOfTest.Runner.exe" list="C:\Users\Usman\Documents\Test Studio Projects\spotify\TestLists\spotify page.aiilist" junit'
